// apps/portfolio/src/components/ui/button.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@josui/core-web";

const buttonVariants = cva(
  cn(
    "group relative inline-flex shrink-0 items-center justify-center whitespace-nowrap",

    "text-foreground/70 hover:text-accent-foreground text-sm font-medium",

    "border-foreground/50 hover:border-accent-foreground/60",

    "cursor-pointer transition-all outline-none disabled:pointer-events-none disabled:opacity-50",

    "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",

    "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",

    "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  ),
  {
    variants: {
      variant: {
        default:
          "border-gray-300 bg-gray-50 text-gray-950 hover:border-gray-300 hover:bg-gray-100/70",
        primary:
          "border-primary-500 hover:bg-primary-200/70 text-primary-950 hover:border-primary-500 bg-primary-100",
        secondary:
          "border-secondary-300 hover:bg-secondary-100/70 text-secondary-950 hover:border-secondary-300 bg-secondary-50/70",
        ghost: "text-inherit",
      },
      size: {
        default: "h-10 px-4 py-2 has-[>svg]:px-3",
        sm: "h-8 gap-1.5 px-3 has-[>svg]:px-2.5",
        lg: "text-md h-12 px-6 has-[>svg]:px-4",
        xl: "h-14 px-8 text-lg has-[>svg]:px-6",
        icon: "size-9",
        "icon-sm": "size-8",
        "icon-lg": "size-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

type ButtonVariants = VariantProps<typeof buttonVariants>;

function Button({
  className,
  variant,
  size,
  asChild = false,
  children,
  ...props
}: React.ComponentProps<"button"> &
  ButtonVariants & {
    asChild?: boolean;
  }) {
  if (asChild) {
    const child = React.Children.only(children) as React.ReactElement<{
      className?: string;
      children?: React.ReactNode;
    }>;
    const mergedClassName = cn(buttonVariants({ variant, size, className }), child.props.className);

    return React.cloneElement(
      child,
      {
        ...props,
        className: mergedClassName,
      },
      <ButtonContent variant={variant}>{child.props.children}</ButtonContent>,
    );
  }

  return (
    <button
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    >
      <ButtonContent variant={variant}>{children}</ButtonContent>
    </button>
  );
}

function ButtonContent({
  children,
  variant,
}: {
  children: React.ReactNode;
  variant: ButtonVariants["variant"];
}) {
  return (
    <>
      <span
        className={cn(
          "absolute inset-y-0 left-0 flex flex-col justify-between border-l",
          "border-inherit opacity-50 transition-all duration-200 ease-in-out",
          variant === "ghost" ? "w-0 opacity-0" : "w-2",
          "group-hover:w-1/2 group-hover:opacity-100",
        )}
      >
        <span className="block w-full border-t border-inherit" />
        <span className="block w-full border-b border-inherit" />
      </span>
      <span className="relative z-10 flex items-center gap-3">{children}</span>
      <span
        className={cn(
          "absolute inset-y-0 right-0 flex flex-col justify-between border-r",
          "border-inherit opacity-50 transition-all duration-200 ease-in-out",
          variant === "ghost" ? "w-0 opacity-0" : "w-2",
          "group-hover:w-1/2 group-hover:opacity-100",
        )}
      >
        <span className="block w-full border-t border-inherit" />
        <span className="block w-full border-b border-inherit" />
      </span>
      {variant !== "ghost" && (
        <span className="absolute inset-0 block border border-inherit opacity-10" />
      )}
    </>
  );
}

export { Button, buttonVariants };

// packages/vue/src/components/Button/Button.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '@josui/core-web';
import Spinner from '../Spinner/Spinner.vue';

export interface ButtonProps {
  /** Visual style variant */
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive';
  /** Size of the button */
  size?: 'sm' | 'md' | 'lg';
  /** Show loading spinner */
  isLoading?: boolean;
  /** Disabled state */
  disabled?: boolean;
  /** Button type */
  type?: 'button' | 'submit' | 'reset';
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  isLoading: false,
  disabled: false,
  type: 'button',
});

const variantStyles = {
  primary:
    'bg-primary-500 text-white hover:bg-primary-600 active:bg-primary-700 focus-visible:ring-primary-500',
  secondary:
    'bg-gray-100 text-gray-900 hover:bg-gray-200 active:bg-gray-300 focus-visible:ring-gray-500',
  outline:
    'border border-gray-300 bg-transparent text-gray-900 hover:bg-gray-50 active:bg-gray-100 focus-visible:ring-gray-500',
  ghost:
    'bg-transparent text-gray-900 hover:bg-gray-100 active:bg-gray-200 focus-visible:ring-gray-500',
  destructive:
    'bg-error-500 text-white hover:bg-error-700 active:bg-error-700 focus-visible:ring-error-500',
};

const sizeStyles = {
  sm: 'h-8 px-3 text-sm gap-1.5',
  md: 'h-10 px-4 text-sm gap-2',
  lg: 'h-12 px-6 text-base gap-2',
};

const classes = computed(() =>
  cn(
    'inline-flex items-center justify-center rounded-md font-medium transition-colors',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2',
    'disabled:pointer-events-none disabled:opacity-50',
    variantStyles[props.variant],
    sizeStyles[props.size]
  )
);

const isDisabled = computed(() => props.disabled || props.isLoading);
const spinnerSize = computed(() => (props.size === 'sm' ? 'sm' : 'md'));
</script>

<template>
  <button :class="classes" :disabled="isDisabled" :type="type">
    <Spinner v-if="isLoading" :size="spinnerSize" class="mr-2" />
    <slot v-else name="leftIcon">
      <span v-if="$slots.leftIcon" class="shrink-0">
        <slot name="leftIcon" />
      </span>
    </slot>
    <slot />
    <span v-if="$slots.rightIcon && !isLoading" class="shrink-0">
      <slot name="rightIcon" />
    </span>
  </button>
</template>
